# Service config to expose Python and Go engines internally.

apiVersion: v1
kind: Service
metadata:
  name: strategy-engine
spec:
  selector:
    app: strategy-engine
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: execution-engine
spec:
  selector:
    app: execution-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
