# Kubernetes Deployment YAML for trading Python and Go microservices.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strategy-engine
  template:
    metadata:
      labels:
        app: strategy-engine
    spec:
      containers:
      - name: strategy-engine
        image: mcmerger/strategy-engine:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: execution-engine
  template:
    metadata:
      labels:
        app: execution-engine
    spec:
      containers:
      - name: execution-engine
        image: mcmerger/execution-engine:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
