# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import execution_pb2 as execution__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutionServiceStub(object):
    """Execution Service - Handles order submission and market data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/signalops.ExecutionService/SubmitOrder',
                request_serializer=execution__pb2.OrderRequest.SerializeToString,
                response_deserializer=execution__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetMarketData = channel.unary_unary(
                '/signalops.ExecutionService/GetMarketData',
                request_serializer=execution__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=execution__pb2.MarketDataResponse.FromString,
                _registered_method=True)
        self.StreamPrices = channel.unary_stream(
                '/signalops.ExecutionService/StreamPrices',
                request_serializer=execution__pb2.StreamRequest.SerializeToString,
                response_deserializer=execution__pb2.PriceUpdate.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/signalops.ExecutionService/GetOrderStatus',
                request_serializer=execution__pb2.OrderStatusRequest.SerializeToString,
                response_deserializer=execution__pb2.OrderStatusResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/signalops.ExecutionService/GetBalance',
                request_serializer=execution__pb2.BalanceRequest.SerializeToString,
                response_deserializer=execution__pb2.BalanceResponse.FromString,
                _registered_method=True)


class ExecutionServiceServicer(object):
    """Execution Service - Handles order submission and market data
    """

    def SubmitOrder(self, request, context):
        """Submit a trading order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketData(self, request, context):
        """Get current market data for a symbol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPrices(self, request, context):
        """Stream real-time price updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Get order status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Get account balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=execution__pb2.OrderRequest.FromString,
                    response_serializer=execution__pb2.OrderResponse.SerializeToString,
            ),
            'GetMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketData,
                    request_deserializer=execution__pb2.MarketDataRequest.FromString,
                    response_serializer=execution__pb2.MarketDataResponse.SerializeToString,
            ),
            'StreamPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrices,
                    request_deserializer=execution__pb2.StreamRequest.FromString,
                    response_serializer=execution__pb2.PriceUpdate.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=execution__pb2.OrderStatusRequest.FromString,
                    response_serializer=execution__pb2.OrderStatusResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=execution__pb2.BalanceRequest.FromString,
                    response_serializer=execution__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signalops.ExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('signalops.ExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionService(object):
    """Execution Service - Handles order submission and market data
    """

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signalops.ExecutionService/SubmitOrder',
            execution__pb2.OrderRequest.SerializeToString,
            execution__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signalops.ExecutionService/GetMarketData',
            execution__pb2.MarketDataRequest.SerializeToString,
            execution__pb2.MarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/signalops.ExecutionService/StreamPrices',
            execution__pb2.StreamRequest.SerializeToString,
            execution__pb2.PriceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signalops.ExecutionService/GetOrderStatus',
            execution__pb2.OrderStatusRequest.SerializeToString,
            execution__pb2.OrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signalops.ExecutionService/GetBalance',
            execution__pb2.BalanceRequest.SerializeToString,
            execution__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
